---
abstract: 'Simulate HTTP Verbs'
author:
  - 'Bernhard Graf C<< <graf at cpan.org> >>'
  - 'Bernhard Graf <graf@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Mojo: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojolicious-Plugin-MethodOverride
no_index:
  directory:
    - inc
    - t
requires:
  Mojolicious: 0
  perl: 5.10.0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/augensalat/Mojolicious-Plugin-MethodOverride/tree/master
version: 0.001
